global:
  resolve_timeout: 1m
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "{{ mail_app_user }}"
  smtp_auth_username: "{{ mail_app_user }}"
  smtp_auth_password: "{{ mail_app_pass }}"
  smtp_require_tls: true

route:
  receiver: "email-notifications"
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

templates:
  - '/etc/alertmanager/template/*.tmpl'

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "{{ mail_app_to }}"
        send_resolved: true
        headers:
          subject: "{% raw %}[OCA {{ .Status | toUpper }}] {{ .GroupLabels.alertname }}{% endraw %}"
        html: "{% raw %}{{ range .Alerts }}
          <h3>Alerta: {{ .Labels.alertname }}</h3>
          <p><a href='http://monitor.oca-portal.com:9093'>Acessar Alert Manager</a></p>
          <p>Status: {{ $.Status }}</p>
          <p>Instância: {{ .Labels.instance }}</p>
          <p>Severidade: {{ .Labels.severity }}</p>
          <p>Data e hora: {{ .StartsAt }}</p>
          <p>Descrição: {{ .Annotations.description }}</p>
          {{ end }}
          {% endraw %}"