route:
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 10s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 30s

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 30m

  # A default receiver
  receiver: "email"

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
    receiver: 'Mail Alert'
  # group_by: [ alertname ]
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

  receivers:
    - name: 'Mail Alert'
      email_configs:
        - smarthost: 'smtp.gmail.com:587'
          #auth_username: ''
          #auth_password: "<your app password here>"
          #from: '<your email id here>'
          to: 'mariane.zeitouni@ccc.ufcg.edu.br'
          headers:
            subject: 'Prometheus Mail Alerts'

