groups:
  - name: AlertsfromOca
    rules:
      - alert: HostOutOfMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < {{ memory_threshold | default(20) }}) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of memory (instance {{ '{{ $labels.instance }}' }})
          description: |
            Node memory is filling up (< {{ memory_threshold | default(20) }}% left)
            VALUE = {{ '{{ $value }}' }}
            LABELS = {{ '{{ $labels }}' }}

      - alert: HostOutOfDiskSpace
        expr: ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < {{ disk_threshold | default(20) }} and ON (instance, device, mountpoint) node_filesystem_readonly == 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Host out of disk space (instance {{ '{{ $labels.instance }}' }})
          description: |
            Disk is almost full (< {{ disk_threshold | default(20) }}% left)
            VALUE = {{ '{{ $value }}' }}
            LABELS = {{ '{{ $labels }}' }}

      - alert: HostHighCpuLoad
        expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!='idle'}[2m]))) > {{ cpu_threshold | default(0.8) }}) * on(instance) group_left (nodename) node_uname_info{nodename=~'.+'}
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ '{{ $labels.instance }}' }})
          description: |
            CPU load is > {{ cpu_threshold | default(0.8) }}%
            VALUE = {{ '{{ $value }}' }}
            LABELS = {{ '{{ $labels }}' }}

      - alert: InstanceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Oca instance down"
          description: "OCA is down" # No Prometheus templating here

      - alert: ServiceDown
        expr: probe_success == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Service is down (instance {{ '{{ $labels.instance }}' }})"
          description: |
            The service is not responding. Probe result: {{ '{{ $value }}' }}
            LABELS = {{ '{{ $labels }}' }}