---
# tasks file for role/deploy
- name: Create a directory for the Nginx configuration
  file:
    path: ./nginx
    state: directory

- name: Create a directory for SSL certificates
  file:
    path: ./ssl
    state: directory

- name: Create the oca.conf file for Nginx
  template:
    src: nginx/oca.conf
    dest: ./nginx/oca.conf

- name: Copy SSL certificates
  template: 
    src: "ssl/{{ item }}"
    dest: ./ssl/
  with_items:
    - ssl.pem
    - ssl.key
    - ssl.crt

- name: Create the docker-compose.yml file
  template:
    src: ./docker-compose.yml
    dest: ./docker-compose.yml

- name: Stop and remove existing container if it is running
  docker_container:
    name: "{{ container_name }}"
    state: absent
    force_kill: yes
  ignore_errors: yes
  vars:
    ansible_docker_host: "unix://var/run/docker.sock"

- name: Pull the OCA image
  community.docker.docker_image:
    name: "{{ docker_image }}:latest"
    source: pull

- name: Run Docker Compose up
  become: True
  shell:
    cmd: "docker compose -f ./docker-compose.yml up -d"
