---
# tasks file for role/deploy
- name: Stop container 
  shell: docker stop {{ container_name }}
  ignore_errors: true

- name: Remove container
  shell: docker rm {{ container_name }}
  ignore_errors: true

- name: Pull image from DockerHub
  shell: "docker pull {{ docker_image }}: {{ tag }}"

- name: Run container
  shell: "docker run -d --name {{ container_name }} -p {{ container_port }}:{{ container_port }} {{ docker_image }}:{{ tag }}"
  ignore_errors: true